services:

  dagster-dagit:
    container_name: dagster-dagit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  dagster-daemon:
    container_name: dagster-daemon
    build:
      context: .
      dockerfile: Dockerfile
    command: "dagster-daemon run"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  dagster-postgres:
    container_name: dagster-postgres
    image: postgres:13.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
    
volumes:
  dagster-postgres:
    driver: local